networks:
  dev:

volumes:
  ollama_data:

services:
  backend:
    build: ./server
    networks:
      - dev

  frontend:
    build: ./frontend
    networks:
      - dev

  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - dev